/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhonghao_java_Java2cpp */

#ifndef _Included_com_zhonghao_java_Java2cpp
#define _Included_com_zhonghao_java_Java2cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhonghao_java_Java2cpp
 * Method:    DLL_ADD
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zhonghao_java_Java2cpp_DLL_1ADD
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zhonghao_java_Java2cpp
 * Method:    DLL_SUB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zhonghao_java_Java2cpp_DLL_1SUB
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zhonghao_java_Java2cpp
 * Method:    DLL_MUL
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zhonghao_java_Java2cpp_DLL_1MUL
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zhonghao_java_Java2cpp
 * Method:    DLL_DIV
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zhonghao_java_Java2cpp_DLL_1DIV
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
